version: "3"


services: 
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - mysql/data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: roootpassword
            MYSQL_DATABASE: master
            MYSQL_USER: user
            MYSQL_ROOT_PASSWORD: password
    
    app:
        build:
            context: .
        container_name: cake-php-app
        image: cake-image
