version: "3"


services:
    db:
        image: mysql:5.6
        restart: always
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: roootpassword
            MYSQL_DATABASE: master
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
          - "3308:3306"

    app:
        build:
            context: .
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        container_name: cake-php-app
        image: cake-image
        ports:
            - 8228:80
